### ISSUE TITLE
The Inspire spell & Ice Blitz

### ISSUE THREAD

**Issue by Heimdallr-1** [ipdnaeip/WizardryNextGeneration#20]
Cannot find the **Inspire spell**.

```
spell.wizardrynextgeneration:inspire=Inspire (?)
spell.wizardrynextgeneration:inspire.desc=Rally your nearby pets and summons. (?)
```
Also, spell.wizardrynextgeneration:ice_blitz=Ice Blitz
spell.wizardrynextgeneration:ice_blitz.desc=Freeze a creature in a block of ice and damage it. (**Does nothing**).

I hope you check the mod in the game?

**Comment by ipdnaeip** [comment]
Regarding Inspire, I did work on it, but didn't fully implement it as I was missing art and wanted to put out an update. I'll release it sometime soon.

Ice Blitz damages and freezes an enemy. It works on my end so I'm unsure as to what you mean.
